# Site Configuration for Setup Your Project for Success Documentation Portal

# Site Information
title: "Setup Your Project for Success"
description: "Essential project design tools for nonprofits and social enterprises to build fundable, impactful, and scalable projects"
url: "https://toolkit.festa.design"
baseurl: ""

# Organization Info
author: "Festa Design Studio"
email: "hello@festa.design"
logo: "/assets/images/festa-logo.png"

# Jekyll Configuration
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Theme Configuration - using remote theme for GitHub Pages
remote_theme: just-the-docs/just-the-docs

# Just-the-docs Theme Settings
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation Structure
nav_sort: case_insensitive
nav_external_links:
  - title: "Festa Design Studio"
    url: "https://festa.design"
    hide_icon: false
  - title: "Watch on Vimeo"
    url: "https://vimeo.com/festa-design-studio"
    hide_icon: false

# Footer Configuration
footer_content: "Copyright &copy; 2025 Festa Design Studio. Empowering purpose-driven organizations through design."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Color Scheme (we'll customize this with Festa colors)
color_scheme: festa

# Google Analytics (replace with your tracking ID)
ga_tracking: G-XXXXXXXXXX

# Social Links
social_links:
  - platform: linkedin
    user_url: "https://linkedin.com/company/festa-design-studio"
  - platform: instagram  
    user_url: "https://instagram.com/festa.design.studio"

# Collections for organizing content
collections:
  lessons:
    output: true
    permalink: /:collection/:name/
  resources:
    output: true
    permalink: /:collection/:name/

# Default layouts for different content types
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "lessons"
    values:
      layout: "default"
      nav_exclude: false
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "default"
      nav_exclude: false

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - "*.txt"
  - comprehensive_prd.md