# Site Configuration for Setup Your Project for Success Documentation Portal

# Site Information
title: "Setup Your Project for Success"
description: "Essential project design tools for nonprofits and social enterprises to build fundable, impactful, and scalable projects"
url: "https://toolkit.festa.design"
baseurl: ""

# Organization Info
author: "Festa Design Studio"
email: "hello@festa.design"
logo: "/assets/images/festa-logo.png"

# Jekyll Configuration
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Theme Configuration - using remote theme for GitHub Pages
remote_theme: just-the-docs/just-the-docs

# Just-the-docs Theme Settings
search_enabled: true
search.heading_level: 2
heading_anchors: true
nav_fold: false
aux_links:
  "GitHub":
    - "//github.com/babayomi/toolkit"

# Navigation
nav_enabled: true
nav_sort: case_sensitive

# Color Scheme (we'll customize this with Festa colors)
color_scheme: festa

# Google Analytics (replace with your tracking ID)
# ga_tracking: G-XXXXXXXXXX

# Collections for organizing content
collections:
  lessons:
    output: true
    permalink: /:collection/:name/
  resources:
    output: true
    permalink: /:collection/:name/

# Default layouts for different content types
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "lessons"
    values:
      layout: "default"
      nav_exclude: false
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "default"
      nav_exclude: false

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - "*.txt"
  - comprehensive_prd.md